// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykynihwaqdwajfcgoxkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlreW5paHdhcWR3YWpmY2dveGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDI4NTMsImV4cCI6MjA1OTc3ODg1M30.eyL9lqeL7JaR_WOZghGnJGy_Xtz7-NehmcWGQzu1p3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);